#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    purge)
	# remove node-restore group and user
	deluser node-restore || true
	delgroup node-restore || true
	# delete /var/log directory
	rm -rf /var/log/node-restore/
	# delete /var/lib directory
	rm -rf /var/lib/node-restore/
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
