#!/bin/sh

set -e

case "$1" in
    configure)
	# create a /var/log directory
	mkdir -p /var/log/node-restore/    
	chown node-restore:node-restore /var/log/node-restore/
	# create a /var/lib directory
	mkdir -p /var/lib/nodejs/restore/
	chown node-restore:node-restore /var/lib/nodejs/restore/
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
