#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    install|upgrade)
	# create a node-restore group
	if ! getent group node-restore >/dev/null 2>&1; then
		addgroup --system node-restore
	fi
	# create a node-restore user
	if ! getent passwd node-restore >/dev/null 2>&1; then
		adduser --system \
			--ingroup node-restore \
			--no-create-home \
			--home /var/lib/node-restore \
			--disabled-password \
			--gecos "reStore Server" \
			node-restore
	fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
