#!/bin/sh

set -e

#DEBHELPER#

case "$1" in
    remove|upgrade|deconfigure)
	# stop node-restore
	invoke-rc.d node-restore stop
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
